name: Build and Package

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Clean workspace
      run: |
        # Полная очистка предыдущих сборок
        rm -rf build || true
        mkdir -p build
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake 
        sudo apt-get install -y libgtest-dev googletest
        
    - name: Build Google Test
      run: |
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib
        
    - name: Configure CMake
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release --fresh
        
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --parallel 2
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Generate DEB package
      run: |
        cd build
        cpack -G DEB
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: factory-pattern-deb
        path: build/*.deb
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.deb
        name: "Build ${{ github.run_number }}"
        body: "Automatic build\nCommit: ${{ github.sha }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
