name: Build and Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev googletest
        
    - name: Build and install Google Test
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib
        sudo cp -r googletest/include/gtest /usr/include
        sudo cp -r googlemock/include/gmock /usr/include
        
    - name: Configure CMake with CPack settings
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCPACK_PACKAGE_NAME="factory-pattern" \
          -DCPACK_PACKAGE_VERSION="1.0.0" \
          -DCPACK_PACKAGE_CONTACT="admin@example.com" \
          -DCPACK_DEBIAN_PACKAGE_MAINTAINER="Package Maintainer <maintainer@example.com>" \
          -DCPACK_DEBIAN_PACKAGE_DEPENDS="libc6 (>= 2.31)"
      
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --parallel 2
      
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Generate DEB package
      run: |
        cd build
        cpack -G DEB --config CPackConfig.cmake
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: factory-pattern-deb
        path: build/*.deb
        
    - name: Create Release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
