name: Build and Package

on:
  push:
    tags:
      - 'v*.*.*'  # Триггерим на теги вида v1.0.0
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev googletest
        
    - name: Build Google Test
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib
        
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
      
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --parallel 2
      
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Generate DEB package
      run: |
        cd build
        cpack -G DEB
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: factory-pattern-deb
        path: build/*.deb
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.deb
        tag_name: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        body: "Factory Pattern DEB package"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
