name: Build and Package

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Clean workspace
      run: rm -rf build && mkdir -p build
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev googletest
        
    - name: Build Google Test
      run: |
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib
        
    - name: Configure CMake
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release --fresh
        
    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --parallel 2
        
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Generate DEB package
      run: |
        cd build
        cpack -G DEB
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: factory-pattern-deb
        path: build/*.deb
        
    - name: Create Release
      uses: actions/create-release@v1
      if: github.ref == 'refs/heads/master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-${{ github.sha }}
        release_name: "Nightly Build ${{ github.run_number }}"
        body: |
          Automatic nightly build
          Commit: ${{ github.sha }}
          Date: ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: true
        artifacts: build/*.deb
