name: Build and Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev googletest
        
    - name: Build and install Google Test
      run: |
        # Новый способ установки GTest в Ubuntu 22.04
        sudo apt-get install -y libgtest-dev
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib
        sudo cp -r googletest/include/gtest /usr/include
        sudo cp -r googlemock/include/gmock /usr/include
        
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Run tests
      run: cd build && ctest --output-on-failure
      
    - name: Create DEB package
      run: |
        cd build
        cpack -G DEB
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: factory-pattern-deb
        path: build/*.deb
        
    - name: Create Release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
