name: Build and Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libgtest-dev \
          dpkg-dev \
          debhelper
        
    - name: Build and Install GTest
      run: |
        cd /usr/src/googletest
        sudo cmake -B build -DCMAKE_BUILD_TYPE=Release
        sudo cmake --build build
        sudo cmake --install build --prefix /usr/local
        sudo ldconfig
        
    - name: Clean and Configure CMake
      run: |
        rm -rf build package
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        
    - name: Build Project
      run: |
        cd build
        cmake --build . --config Release --parallel 2
        
    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Prepare Package Structure
      run: |
        mkdir -p package/usr/bin
        mkdir -p package/usr/lib
        cp build/character_demo package/usr/bin/
        cp build/libcharacter_factory.a package/usr/lib/
        
        mkdir -p package/DEBIAN
        cat > package/DEBIAN/control <<'EOF'
Package: factory-pattern
Version: 1.0-$(date +%Y%m%d%H%M)
Section: base
Priority: optional
Architecture: amd64
Maintainer: anipuka <annakupina2006@yandex.ru>
Description: Factory Pattern Example Implementation
EOF
        
    - name: Build DEB Package
      run: |
        dpkg-deb --build package factory-pattern.deb
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: factory-pattern-package
        path: factory-pattern.deb
        
    - name: Create Release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: factory-pattern.deb
        tag_name: v1.0-$(date +%Y%m%d%H%M)
        body: "Automatic build of factory pattern implementation"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
